# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Mat Greten"
email: "matgreten@protonmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Feature development and bug squashing, backed by 10+ years of customer service and technical support experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matgreten.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  "meagerfindings"
repository: "meagerfindings/matgreten.dev"

author:
  name: "Mat Greten"
  avatar: "/images/profile/fourpass.jpg"
  bio: "A glass can only spill what it contains." # Note: Markdown is allowed
  location: "Colorado"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/meagerfindings"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/meagerfindings"
    - label: "Keybase"
      icon: "fab fa-keybase"
      url: "https://keybase.io/meagerfindings"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/matthewgreten/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/meagerfindings"


# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: "/portfolio"
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
  # _posts
  - scope:
      path: "/posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/meagerfindings"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/meagerfindings"
    - label: "Keybase"
      icon: "fab fa-keybase"
      url: "https://keybase.io/meagerfindings"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/matthewgreten/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/meagerfindings"
